# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1_kxey2yaxRmjYoWl-H-xZY0iN5qIuP
"""

class Animal:
    def __init__(self, name):
        self.name = name

    def eat(self):
        print(f"{self.name} Animal is eating.")

    def sleep(self):
        print(f"{self.name} Animal is sleeping.")


class Dog(Animal):
    def bark(self):
        print(f"{self.name} Dog is barking.")
    def eat(self):
        print(f"{self.name} Dog is eating.")

    def sleep(self):
        print(f"{self.name} Dog is sleeping.")


class Cat(Animal):
    def meow(self):
        print(f"{self.name} Cat is meowing.")
    def eat(self):
        print(f"{self.name} Cat is eating.")

    def sleep(self):
        print(f"{self.name} Cat sleeping.")


dog = Dog("Buddy")
dog.eat()
dog.sleep()
dog.bark()


cat = Cat("Whiskers")
cat.eat()
cat.sleep()
cat.meow()